/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalStaffRouteImport } from './routes/_portal.staff'
import { Route as PortalSearchRouteImport } from './routes/_portal.search'
import { Route as PortalInteractionsRouteImport } from './routes/_portal.interactions'
import { Route as PortalDashboardRouteImport } from './routes/_portal.dashboard'
import { Route as PortalAdminRouteImport } from './routes/_portal.admin'
import { Route as PortalStaffIdRouteImport } from './routes/_portal.staff.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStaffRoute = PortalStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSearchRoute = PortalSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInteractionsRoute = PortalInteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStaffIdRoute = PortalStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalStaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof PortalAdminRoute
  '/dashboard': typeof PortalDashboardRoute
  '/interactions': typeof PortalInteractionsRoute
  '/search': typeof PortalSearchRoute
  '/staff': typeof PortalStaffRouteWithChildren
  '/staff/$id': typeof PortalStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof PortalAdminRoute
  '/dashboard': typeof PortalDashboardRoute
  '/interactions': typeof PortalInteractionsRoute
  '/search': typeof PortalSearchRoute
  '/staff': typeof PortalStaffRouteWithChildren
  '/staff/$id': typeof PortalStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_portal/admin': typeof PortalAdminRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/interactions': typeof PortalInteractionsRoute
  '/_portal/search': typeof PortalSearchRoute
  '/_portal/staff': typeof PortalStaffRouteWithChildren
  '/_portal/staff/$id': typeof PortalStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/interactions'
    | '/search'
    | '/staff'
    | '/staff/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/interactions'
    | '/search'
    | '/staff'
    | '/staff/$id'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_portal/admin'
    | '/_portal/dashboard'
    | '/_portal/interactions'
    | '/_portal/search'
    | '/_portal/staff'
    | '/_portal/staff/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/staff': {
      id: '/_portal/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof PortalStaffRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/search': {
      id: '/_portal/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PortalSearchRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/interactions': {
      id: '/_portal/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof PortalInteractionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin': {
      id: '/_portal/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/staff/$id': {
      id: '/_portal/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof PortalStaffIdRouteImport
      parentRoute: typeof PortalStaffRoute
    }
  }
}

interface PortalStaffRouteChildren {
  PortalStaffIdRoute: typeof PortalStaffIdRoute
}

const PortalStaffRouteChildren: PortalStaffRouteChildren = {
  PortalStaffIdRoute: PortalStaffIdRoute,
}

const PortalStaffRouteWithChildren = PortalStaffRoute._addFileChildren(
  PortalStaffRouteChildren,
)

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalInteractionsRoute: typeof PortalInteractionsRoute
  PortalSearchRoute: typeof PortalSearchRoute
  PortalStaffRoute: typeof PortalStaffRouteWithChildren
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalInteractionsRoute: PortalInteractionsRoute,
  PortalSearchRoute: PortalSearchRoute,
  PortalStaffRoute: PortalStaffRouteWithChildren,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
