/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTutorialRouteImport } from './routes/_portal.tutorial'
import { Route as PortalSupportRouteImport } from './routes/_portal.support'
import { Route as PortalStatsRouteImport } from './routes/_portal.stats'
import { Route as PortalStaffRouteImport } from './routes/_portal.staff'
import { Route as PortalSpecLogRouteImport } from './routes/_portal.spec-log'
import { Route as PortalSearchRouteImport } from './routes/_portal.search'
import { Route as PortalScheduleRouteImport } from './routes/_portal.schedule'
import { Route as PortalProfileRouteImport } from './routes/_portal.profile'
import { Route as PortalPostersRouteImport } from './routes/_portal.posters'
import { Route as PortalMentoringRouteImport } from './routes/_portal.mentoring'
import { Route as PortalLeaderboardRouteImport } from './routes/_portal.leaderboard'
import { Route as PortalInteractionsRouteImport } from './routes/_portal.interactions'
import { Route as PortalHallRouteImport } from './routes/_portal.hall'
import { Route as PortalDashboardRouteImport } from './routes/_portal.dashboard'
import { Route as PortalCompRouteImport } from './routes/_portal.comp'
import { Route as PortalArchivesRouteImport } from './routes/_portal.archives'
import { Route as PortalAnnouncementsRouteImport } from './routes/_portal.announcements'
import { Route as PortalAdminRouteImport } from './routes/_portal.admin'
import { Route as PortalStaffIdRouteImport } from './routes/_portal.staff.$id'
import { Route as PortalScheduleEventsRouteImport } from './routes/_portal.schedule.events'
import { Route as PortalScheduleEntertainmentRouteImport } from './routes/_portal.schedule.entertainment'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTutorialRoute = PortalTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatsRoute = PortalStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStaffRoute = PortalStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSpecLogRoute = PortalSpecLogRouteImport.update({
  id: '/spec-log',
  path: '/spec-log',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSearchRoute = PortalSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PortalRoute,
} as any)
const PortalScheduleRoute = PortalScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPostersRoute = PortalPostersRouteImport.update({
  id: '/posters',
  path: '/posters',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMentoringRoute = PortalMentoringRouteImport.update({
  id: '/mentoring',
  path: '/mentoring',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLeaderboardRoute = PortalLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInteractionsRoute = PortalInteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHallRoute = PortalHallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCompRoute = PortalCompRouteImport.update({
  id: '/comp',
  path: '/comp',
  getParentRoute: () => PortalRoute,
} as any)
const PortalArchivesRoute = PortalArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnnouncementsRoute = PortalAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStaffIdRoute = PortalStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalScheduleEventsRoute = PortalScheduleEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PortalScheduleRoute,
} as any)
const PortalScheduleEntertainmentRoute =
  PortalScheduleEntertainmentRouteImport.update({
    id: '/entertainment',
    path: '/entertainment',
    getParentRoute: () => PortalScheduleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof PortalAdminRoute
  '/announcements': typeof PortalAnnouncementsRoute
  '/archives': typeof PortalArchivesRoute
  '/comp': typeof PortalCompRoute
  '/dashboard': typeof PortalDashboardRoute
  '/hall': typeof PortalHallRoute
  '/interactions': typeof PortalInteractionsRoute
  '/leaderboard': typeof PortalLeaderboardRoute
  '/mentoring': typeof PortalMentoringRoute
  '/posters': typeof PortalPostersRoute
  '/profile': typeof PortalProfileRoute
  '/schedule': typeof PortalScheduleRouteWithChildren
  '/search': typeof PortalSearchRoute
  '/spec-log': typeof PortalSpecLogRoute
  '/staff': typeof PortalStaffRouteWithChildren
  '/stats': typeof PortalStatsRoute
  '/support': typeof PortalSupportRoute
  '/tutorial': typeof PortalTutorialRoute
  '/schedule/entertainment': typeof PortalScheduleEntertainmentRoute
  '/schedule/events': typeof PortalScheduleEventsRoute
  '/staff/$id': typeof PortalStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof PortalAdminRoute
  '/announcements': typeof PortalAnnouncementsRoute
  '/archives': typeof PortalArchivesRoute
  '/comp': typeof PortalCompRoute
  '/dashboard': typeof PortalDashboardRoute
  '/hall': typeof PortalHallRoute
  '/interactions': typeof PortalInteractionsRoute
  '/leaderboard': typeof PortalLeaderboardRoute
  '/mentoring': typeof PortalMentoringRoute
  '/posters': typeof PortalPostersRoute
  '/profile': typeof PortalProfileRoute
  '/schedule': typeof PortalScheduleRouteWithChildren
  '/search': typeof PortalSearchRoute
  '/spec-log': typeof PortalSpecLogRoute
  '/staff': typeof PortalStaffRouteWithChildren
  '/stats': typeof PortalStatsRoute
  '/support': typeof PortalSupportRoute
  '/tutorial': typeof PortalTutorialRoute
  '/schedule/entertainment': typeof PortalScheduleEntertainmentRoute
  '/schedule/events': typeof PortalScheduleEventsRoute
  '/staff/$id': typeof PortalStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_portal/admin': typeof PortalAdminRoute
  '/_portal/announcements': typeof PortalAnnouncementsRoute
  '/_portal/archives': typeof PortalArchivesRoute
  '/_portal/comp': typeof PortalCompRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/hall': typeof PortalHallRoute
  '/_portal/interactions': typeof PortalInteractionsRoute
  '/_portal/leaderboard': typeof PortalLeaderboardRoute
  '/_portal/mentoring': typeof PortalMentoringRoute
  '/_portal/posters': typeof PortalPostersRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/_portal/schedule': typeof PortalScheduleRouteWithChildren
  '/_portal/search': typeof PortalSearchRoute
  '/_portal/spec-log': typeof PortalSpecLogRoute
  '/_portal/staff': typeof PortalStaffRouteWithChildren
  '/_portal/stats': typeof PortalStatsRoute
  '/_portal/support': typeof PortalSupportRoute
  '/_portal/tutorial': typeof PortalTutorialRoute
  '/_portal/schedule/entertainment': typeof PortalScheduleEntertainmentRoute
  '/_portal/schedule/events': typeof PortalScheduleEventsRoute
  '/_portal/staff/$id': typeof PortalStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/setup'
    | '/signup'
    | '/sitemap.xml'
    | '/admin'
    | '/announcements'
    | '/archives'
    | '/comp'
    | '/dashboard'
    | '/hall'
    | '/interactions'
    | '/leaderboard'
    | '/mentoring'
    | '/posters'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/spec-log'
    | '/staff'
    | '/stats'
    | '/support'
    | '/tutorial'
    | '/schedule/entertainment'
    | '/schedule/events'
    | '/staff/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-password'
    | '/setup'
    | '/signup'
    | '/sitemap.xml'
    | '/admin'
    | '/announcements'
    | '/archives'
    | '/comp'
    | '/dashboard'
    | '/hall'
    | '/interactions'
    | '/leaderboard'
    | '/mentoring'
    | '/posters'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/spec-log'
    | '/staff'
    | '/stats'
    | '/support'
    | '/tutorial'
    | '/schedule/entertainment'
    | '/schedule/events'
    | '/staff/$id'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/login'
    | '/set-password'
    | '/setup'
    | '/signup'
    | '/sitemap.xml'
    | '/_portal/admin'
    | '/_portal/announcements'
    | '/_portal/archives'
    | '/_portal/comp'
    | '/_portal/dashboard'
    | '/_portal/hall'
    | '/_portal/interactions'
    | '/_portal/leaderboard'
    | '/_portal/mentoring'
    | '/_portal/posters'
    | '/_portal/profile'
    | '/_portal/schedule'
    | '/_portal/search'
    | '/_portal/spec-log'
    | '/_portal/staff'
    | '/_portal/stats'
    | '/_portal/support'
    | '/_portal/tutorial'
    | '/_portal/schedule/entertainment'
    | '/_portal/schedule/events'
    | '/_portal/staff/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/tutorial': {
      id: '/_portal/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof PortalTutorialRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/support': {
      id: '/_portal/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/stats': {
      id: '/_portal/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof PortalStatsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/staff': {
      id: '/_portal/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof PortalStaffRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/spec-log': {
      id: '/_portal/spec-log'
      path: '/spec-log'
      fullPath: '/spec-log'
      preLoaderRoute: typeof PortalSpecLogRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/search': {
      id: '/_portal/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PortalSearchRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/schedule': {
      id: '/_portal/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof PortalScheduleRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/posters': {
      id: '/_portal/posters'
      path: '/posters'
      fullPath: '/posters'
      preLoaderRoute: typeof PortalPostersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/mentoring': {
      id: '/_portal/mentoring'
      path: '/mentoring'
      fullPath: '/mentoring'
      preLoaderRoute: typeof PortalMentoringRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/leaderboard': {
      id: '/_portal/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof PortalLeaderboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/interactions': {
      id: '/_portal/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof PortalInteractionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/hall': {
      id: '/_portal/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof PortalHallRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/comp': {
      id: '/_portal/comp'
      path: '/comp'
      fullPath: '/comp'
      preLoaderRoute: typeof PortalCompRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/archives': {
      id: '/_portal/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof PortalArchivesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/announcements': {
      id: '/_portal/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof PortalAnnouncementsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/admin': {
      id: '/_portal/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/staff/$id': {
      id: '/_portal/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof PortalStaffIdRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/_portal/schedule/events': {
      id: '/_portal/schedule/events'
      path: '/events'
      fullPath: '/schedule/events'
      preLoaderRoute: typeof PortalScheduleEventsRouteImport
      parentRoute: typeof PortalScheduleRoute
    }
    '/_portal/schedule/entertainment': {
      id: '/_portal/schedule/entertainment'
      path: '/entertainment'
      fullPath: '/schedule/entertainment'
      preLoaderRoute: typeof PortalScheduleEntertainmentRouteImport
      parentRoute: typeof PortalScheduleRoute
    }
  }
}

interface PortalScheduleRouteChildren {
  PortalScheduleEntertainmentRoute: typeof PortalScheduleEntertainmentRoute
  PortalScheduleEventsRoute: typeof PortalScheduleEventsRoute
}

const PortalScheduleRouteChildren: PortalScheduleRouteChildren = {
  PortalScheduleEntertainmentRoute: PortalScheduleEntertainmentRoute,
  PortalScheduleEventsRoute: PortalScheduleEventsRoute,
}

const PortalScheduleRouteWithChildren = PortalScheduleRoute._addFileChildren(
  PortalScheduleRouteChildren,
)

interface PortalStaffRouteChildren {
  PortalStaffIdRoute: typeof PortalStaffIdRoute
}

const PortalStaffRouteChildren: PortalStaffRouteChildren = {
  PortalStaffIdRoute: PortalStaffIdRoute,
}

const PortalStaffRouteWithChildren = PortalStaffRoute._addFileChildren(
  PortalStaffRouteChildren,
)

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalAnnouncementsRoute: typeof PortalAnnouncementsRoute
  PortalArchivesRoute: typeof PortalArchivesRoute
  PortalCompRoute: typeof PortalCompRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalHallRoute: typeof PortalHallRoute
  PortalInteractionsRoute: typeof PortalInteractionsRoute
  PortalLeaderboardRoute: typeof PortalLeaderboardRoute
  PortalMentoringRoute: typeof PortalMentoringRoute
  PortalPostersRoute: typeof PortalPostersRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalScheduleRoute: typeof PortalScheduleRouteWithChildren
  PortalSearchRoute: typeof PortalSearchRoute
  PortalSpecLogRoute: typeof PortalSpecLogRoute
  PortalStaffRoute: typeof PortalStaffRouteWithChildren
  PortalStatsRoute: typeof PortalStatsRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalTutorialRoute: typeof PortalTutorialRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalAnnouncementsRoute: PortalAnnouncementsRoute,
  PortalArchivesRoute: PortalArchivesRoute,
  PortalCompRoute: PortalCompRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalHallRoute: PortalHallRoute,
  PortalInteractionsRoute: PortalInteractionsRoute,
  PortalLeaderboardRoute: PortalLeaderboardRoute,
  PortalMentoringRoute: PortalMentoringRoute,
  PortalPostersRoute: PortalPostersRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalScheduleRoute: PortalScheduleRouteWithChildren,
  PortalSearchRoute: PortalSearchRoute,
  PortalSpecLogRoute: PortalSpecLogRoute,
  PortalStaffRoute: PortalStaffRouteWithChildren,
  PortalStatsRoute: PortalStatsRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalTutorialRoute: PortalTutorialRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
